# Deployment Configuration
deployment:
  type: "self_hosted"

base_url: http://localhost:3000
  
features:
  allow_uninvited_signups: true
  allow_multiple_organizations: true
  verify_emails: false

google_oauth:
  enabled: false
  client_id: ${MC_GOOGLE_CLIENT_ID}
  client_secret: ${MC_GOOGLE_CLIENT_SECRET}

smtp_settings:
  host: "smtp.resend.com"
  port: 587
  username: "resend"
  password: ${MC_SMTP_PASSWORD}

encryption_key: ${MC_ENCRYPTION_KEY}

intercom:
  enabled: false

database:
  url: ${MC_DATABASE_URL}