apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
  labels:
    app: metricchatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricchatapp
  template:
    metadata:
      labels:
        app: metricchatapp
    spec:
      {{- if .Values.postgresql.primary.nodeSelector }}
      nodeSelector: {{ .Values.postgresql.primary.nodeSelector | toJson }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: metricchatapp
        image: {{.Values.image}}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        envFrom:
          - configMapRef:
              name: metricchatapp
          {{- if not (empty .Values.config.secretRef) }}
          - secretRef:
              name: {{ .Values.config.secretRef }}
          {{- end }}
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
          - name: metricchat-config
            mountPath: /app/metricchat.yaml
            subPath: metricchatConfig
      volumes:
        - name: metricchat-config
          configMap:
            name: metricchatapp

