apiVersion: v1
kind: Service
metadata:
  name: metricchatapp
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  selector:
    app: metricchatapp
  ports:
    - name: http
      port: 3000
      targetPort: 3000