apiVersion: v2
name: metricchat
description: MetricChat - AI-powered analytics agent for your data stack
type: application
version: 1.0.7
appVersion: 1.0.1
dependencies:
  - name: postgresql
    version: 16.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
